version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POPUT_SECRET_KEY=supersecretkey

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
